project_id = "mmkornqvbafkricqixgk"

[auth]
  [auth.external]
    [auth.external.discord]
      client_id = "env(DISCORD_CLIENT_ID)"
      enabled = true
      secret = "env(DISCORD_CLIENT_SECRET)"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.discord-order-notification]
    verify_jwt = false
  [functions.discord-registration-notification]
    verify_jwt = false
  [functions.validate-trial]
    verify_jwt = false
  [functions.verify-solana-payment]
    verify_jwt = false
  [functions.send-welcome-offer]
    verify_jwt = false
